version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
conda:
  environment: .rtd-environment.yml
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
python:
  install:
    - method: pip
      extra_requirements:
        - all
        - docs
      path: .
