version: 2
jobs:
  twine-check:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python -m pip install -U --user build
      - run: python -m build . --sdist
      - run: python -m pip install -U --user twine
      - run: python -m twine check dist/*
workflows:
  version: 2
  twine-check:
    jobs:
      - twine-check
